package com.learn.api.security;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-09-14T08:36:20.434+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "IauthCheckService", 
                  wsdlLocation = "file:/D:/apache-cxf-3.1.6/authCheck.xml",
                  targetNamespace = "http://controller.web.phicomm.com/") 
public class IauthCheckService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controller.web.phicomm.com/", "IauthCheckService");
    public final static QName IauthCheckPort = new QName("http://controller.web.phicomm.com/", "IauthCheckPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/apache-cxf-3.1.6/authCheck.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IauthCheckService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/apache-cxf-3.1.6/authCheck.xml");
        }
        WSDL_LOCATION = url;
    }

    public IauthCheckService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IauthCheckService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IauthCheckService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IauthCheckService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IauthCheckService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IauthCheckService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IauthCheck
     */
    @WebEndpoint(name = "IauthCheckPort")
    public IauthCheck getIauthCheckPort() {
        return super.getPort(IauthCheckPort, IauthCheck.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IauthCheck
     */
    @WebEndpoint(name = "IauthCheckPort")
    public IauthCheck getIauthCheckPort(WebServiceFeature... features) {
        return super.getPort(IauthCheckPort, IauthCheck.class, features);
    }

}
