package com.learn.api.tHandheld_Device_asmx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-12-15T12:57:52.357+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "tHandheld_Device", 
                  wsdlLocation = "file:/C:/Users/Shinelon/Desktop/tHandheld_Device.asmx.xml",
                  targetNamespace = "http://tempuri.org/") 
public class THandheldDevice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "tHandheld_Device");
    public final static QName THandheldDeviceSoap = new QName("http://tempuri.org/", "tHandheld_DeviceSoap");
    public final static QName THandheldDeviceSoap12 = new QName("http://tempuri.org/", "tHandheld_DeviceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Shinelon/Desktop/tHandheld_Device.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(THandheldDevice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Shinelon/Desktop/tHandheld_Device.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public THandheldDevice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public THandheldDevice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public THandheldDevice() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public THandheldDevice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public THandheldDevice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public THandheldDevice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns THandheldDeviceSoap
     */
    @WebEndpoint(name = "tHandheld_DeviceSoap")
    public THandheldDeviceSoap getTHandheldDeviceSoap() {
        return super.getPort(THandheldDeviceSoap, THandheldDeviceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns THandheldDeviceSoap
     */
    @WebEndpoint(name = "tHandheld_DeviceSoap")
    public THandheldDeviceSoap getTHandheldDeviceSoap(WebServiceFeature... features) {
        return super.getPort(THandheldDeviceSoap, THandheldDeviceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns THandheldDeviceSoap
     */
    @WebEndpoint(name = "tHandheld_DeviceSoap12")
    public THandheldDeviceSoap getTHandheldDeviceSoap12() {
        return super.getPort(THandheldDeviceSoap12, THandheldDeviceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns THandheldDeviceSoap
     */
    @WebEndpoint(name = "tHandheld_DeviceSoap12")
    public THandheldDeviceSoap getTHandheldDeviceSoap12(WebServiceFeature... features) {
        return super.getPort(THandheldDeviceSoap12, THandheldDeviceSoap.class, features);
    }

}
