package com.learn.api.tHandheld_Device_asmx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-12-15T12:57:52.317+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "tHandheld_DeviceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface THandheldDeviceSoap {

    @WebMethod(operationName = "GetUserInfo", action = "http://tempuri.org/GetUserInfo")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetUserInfo")
    @ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetUserInfoResponse")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://tempuri.org/")
    public String getUserInfo(
            @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
                    String json,
            @WebParam(name = "Fields", targetNamespace = "http://tempuri.org/")
                    String fields
    );

    @WebMethod(operationName = "GetPackModelParameters", action = "http://tempuri.org/GetPackModelParameters")
    @RequestWrapper(localName = "GetPackModelParameters", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetPackModelParameters")
    @ResponseWrapper(localName = "GetPackModelParametersResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetPackModelParametersResponse")
    @WebResult(name = "GetPackModelParametersResult", targetNamespace = "http://tempuri.org/")
    public String getPackModelParameters(
            @WebParam(name = "Model", targetNamespace = "http://tempuri.org/")
                    String model,
            @WebParam(name = "ver", targetNamespace = "http://tempuri.org/")
                    String ver
    );

    @WebMethod(operationName = "GetLineList", action = "http://tempuri.org/GetLineList")
    @RequestWrapper(localName = "GetLineList", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetLineList")
    @ResponseWrapper(localName = "GetLineListResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetLineListResponse")
    @WebResult(name = "GetLineListResult", targetNamespace = "http://tempuri.org/")
    public String getLineList();

    @WebMethod(operationName = "Check_SmtWoMerge", action = "http://tempuri.org/Check_SmtWoMerge")
    @RequestWrapper(localName = "Check_SmtWoMerge", targetNamespace = "http://tempuri.org/", className = "com.eq.client.CheckSmtWoMerge")
    @ResponseWrapper(localName = "Check_SmtWoMergeResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.CheckSmtWoMergeResponse")
    @WebResult(name = "Check_SmtWoMergeResult", targetNamespace = "http://tempuri.org/")
    public String checkSmtWoMerge(
            @WebParam(name = "Old_woId", targetNamespace = "http://tempuri.org/")
                    String oldWoId,
            @WebParam(name = "New_woId", targetNamespace = "http://tempuri.org/")
                    String newWoId
    );

    @WebMethod(operationName = "Get_WoInfo", action = "http://tempuri.org/Get_WoInfo")
    @RequestWrapper(localName = "Get_WoInfo", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetWoInfo")
    @ResponseWrapper(localName = "Get_WoInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetWoInfoResponse")
    @WebResult(name = "Get_WoInfoResult", targetNamespace = "http://tempuri.org/")
    public String getWoInfo(
            @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
                    String json,
            @WebParam(name = "Fields", targetNamespace = "http://tempuri.org/")
                    String fields
    );

    @WebMethod(operationName = "Update_SmtKpMonitor", action = "http://tempuri.org/Update_SmtKpMonitor")
    @RequestWrapper(localName = "Update_SmtKpMonitor", targetNamespace = "http://tempuri.org/", className = "com.eq.client.UpdateSmtKpMonitor")
    @ResponseWrapper(localName = "Update_SmtKpMonitorResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.UpdateSmtKpMonitorResponse")
    @WebResult(name = "Update_SmtKpMonitorResult", targetNamespace = "http://tempuri.org/")
    public String updateSmtKpMonitor(
            @WebParam(name = "woId", targetNamespace = "http://tempuri.org/")
                    String woId,
            @WebParam(name = "OldMaterId", targetNamespace = "http://tempuri.org/")
                    String oldMaterId,
            @WebParam(name = "NewMasterId", targetNamespace = "http://tempuri.org/")
                    String newMasterId,
            @WebParam(name = "Machine", targetNamespace = "http://tempuri.org/")
                    String machine
    );

    @WebMethod(operationName = "GetPalletInfo", action = "http://tempuri.org/GetPalletInfo")
    @RequestWrapper(localName = "GetPalletInfo", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetPalletInfo")
    @ResponseWrapper(localName = "GetPalletInfoResponse", targetNamespace = "http://tempuri" +
            ".org/", className = "com.eq.client.GetPalletInfoResponse")
    @WebResult(name = "GetPalletInfoResult", targetNamespace = "http://tempuri.org/")
    public String getPalletInfo(
            @WebParam(name = "dicstring", targetNamespace = "http://tempuri.org/")
                    String dicstring
    );

    @WebMethod(operationName = "Insert_Smt_woMerage", action = "http://tempuri.org/Insert_Smt_woMerage")
    @RequestWrapper(localName = "Insert_Smt_woMerage", targetNamespace = "http://tempuri.org/", className = "com.eq.client.InsertSmtWoMerage")
    @ResponseWrapper(localName = "Insert_Smt_woMerageResponse", targetNamespace = "http://tempuri" +
            ".org/", className = "com.eq.client.InsertSmtWoMerageResponse")
    @WebResult(name = "Insert_Smt_woMerageResult", targetNamespace = "http://tempuri.org/")
    public String insertSmtWoMerage(
            @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
                    String json
    );

    @WebMethod(operationName = "Get_TrSn_Info", action = "http://tempuri.org/Get_TrSn_Info")
    @RequestWrapper(localName = "Get_TrSn_Info", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetTrSnInfo")
    @ResponseWrapper(localName = "Get_TrSn_InfoResponse", targetNamespace = "http://tempuri" +
            ".org/", className = "com.eq.client.GetTrSnInfoResponse")
    @WebResult(name = "Get_TrSn_InfoResult", targetNamespace = "http://tempuri.org/")
    public String getTrSnInfo(
            @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
                    String json,
            @WebParam(name = "Fields", targetNamespace = "http://tempuri.org/")
                    String fields
    );

    @WebMethod(operationName = "GetAllCraftInfo", action = "http://tempuri.org/GetAllCraftInfo")
    @RequestWrapper(localName = "GetAllCraftInfo", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetAllCraftInfo")
    @ResponseWrapper(localName = "GetAllCraftInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetAllCraftInfoResponse")
    @WebResult(name = "GetAllCraftInfoResult", targetNamespace = "http://tempuri.org/")
    public String getAllCraftInfo();

    @WebMethod(operationName = "GetWipTracking", action = "http://tempuri.org/GetWipTracking")
    @RequestWrapper(localName = "GetWipTracking", targetNamespace = "http://tempuri.org/", className = "com.eq.client.GetWipTracking")
    @ResponseWrapper(localName = "GetWipTrackingResponse", targetNamespace = "http://tempuri" +
            ".org/", className = "com.eq.client.GetWipTrackingResponse")
    @WebResult(name = "GetWipTrackingResult", targetNamespace = "http://tempuri.org/")
    public String getWipTracking(
            @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
                    String json,
            @WebParam(name = "Fields", targetNamespace = "http://tempuri.org/")
                    String fields
    );
}
